- App/frontend/src/components/QuestionInput/QuestionInput.module.css
- App/frontend/src/components/SidebarView/SidebarView.module.css
- App/frontend/src/components/SidebarView/SidebarView.tsx
- App/frontend/src/pages/chat/Chat.module.css
Bug : https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4865
1. High Contrast modes
Open BYOAI URL.
Go to system setting ->Accessibility->Contrast themes->select aquatic in drop down-> apply.
Go to BYOAI URL, you can find the screen, outer border is not visible
Expected result: By providing borders to the fields.
> fix: [Bug-4865] Added css for highcContrast modes

- App/frontend/src/components/SidebarView/ArticleView/ArticleView.tsx
- App/frontend/src/components/SidebarView/SidebarView.module.css
- App/frontend/src/pages/chat/Chat.tsx
- App/frontend/src/pages/layout/Layout.tsx
Bug:  https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4424/
**1. Automated check: color-contrast**
Title: WCAG 1.4.3: Elements must meet minimum color contrast ratio thresholds (.css-113)
Tags: Accessibility, WCAG 1.4.3, color-contrast
Issue: Elements must meet minimum color contrast ratio thresholds (color-contrast - https://accessibilityinsights.io/info-examples/web/color-contrast)
Target application: Grant Writer - https://pbn-app-service.azurewebsites.net/
Element path: ._chatContainer_196nq_18 > .css-113
Snippet: <span class="css-113" style="color: rgb(121, 119, 117); margin-left: 15px; margin-top: 25px; align-self: start;">Explore scientific journals</span>
Fix the following:
Element has insufficient color contrast of 4.45 (foreground color: #797775, background …
> fix: [BUG-4424] Added accessibility UI changes for articles

- App/frontend/src/pages/chat/Chat.module.css
Bug : https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4443
High Contrast modes
Open BYOAI URL.
Go to system setting ->Accessibility->Contrast themes->select aquatic in drop down-> apply.
Go to BYOAI URL, you can find the screen, outer border is not visible
Expected result: By providing borders to the fields.
> fix: added citation panel border

- App/frontend/src/components/DraftDocumentsView/DraftDocumentsView.tsx
- App/frontend/src/components/SidebarView/ArticleView/ArticleView.tsx
- App/frontend/src/components/SidebarView/GrantView/GrantView.tsx
- App/frontend/src/pages/chat/Chat.tsx
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4475
**Heading**
Open BYOAI URL
Click on grants: 
Here "Explore grant documents" are not marked as heading and the heading level is like H1 and H4
Click on articles: 
Here "Explore scientific journals" are not marked as heading and the heading level is like H1 and H4
Overlapping cleaner icon so added padding
Click on Drafts
Here "Draft grant proposal" are not marked as heading and the heading level is like H1 and H4
Expected result: Need to mark as heading and Heading level should be in order H1, H2 ...... and order cannot be skipped.
Expected result: Need to mark as heading
> fix: added heading[drafts] and also added button title and label for remove icon[grants and articles]

- ClientAdvisor/AzureFunction/function_app.py
**Bug 5549 :Chatbot can give competing answers about freshness of client asset data**
**Before Fix:** (Recent dates are different in both the responses)
**After Fix:** (Recent dates are same now in all the responses)
Have made the necessary fix and now the bug is solved 
**Bug 5602:Chatbot cannot distinguish between "this client" and a client mentioned by name**
**Before Fix:** (AI is confused b/w this and client name)
**After Fix:** (AI is able to identify this and client name as same now)
have made the changes below is the screenshot attached
> Fix: Chatbot Client Context Recognition and Asset Data Consistency Bugs

- ResearchAssistant/App/app.py
- ResearchAssistant/App/frontend/src/pages/chat/Chat.tsx
Fix for There is no appropriate response when attempting to generate an unethical question on the Articles and Grants pages (Handle Exception)
**Sample Output:**
Unethical Question:
Rate Limit Error:
General Exception:
> Fix for There is no appropriate response when attempting to generate an unethical question on the Articles and Grants pages (Handle Exception)

- ClientAdvisor/AzureFunction/function_app.py
**Bug 5292 - Left panel shows an upcoming scheduled meeting, but chat responses says we have none**
**Before fix:** (Dates were not coming properly)
Note: Occasionally, it also responded with: **"I cannot provide an answer based on the available data. Please rephrase your question or provide more details"** even when data was available.
**After Fix:** (Data is coming properly with proper date and time)
> Fix: Updated the system message to accurately fetch data for upcoming scheduled meetings.

- ClientAdvisor/AzureFunction/function_app.py
Notice when you launch the experience the user arrives at this landing page:
Launch the experience
Show in this screenshot. Left panel has times such as 4:00PM but chatbot responses are showing times as 19:00 hours. Seems inconsistent and should all be the same.
*  Get the code
```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```
* Test the code
```
```
Verify that the following are valid:
time format should be same for side panel and chat response
Validate CSS.
* ...
> fix 24hrs time format chat response

- ClientAdvisor/App/frontend/src/components/ChatHistory/ChatHistoryPanel.tsx
- ClientAdvisor/App/frontend/src/pages/chat/Chat.tsx
_Conversation not found error for delete all chat history during response loading_
While generating AI response we will disable to avoid issues 
- Disabled clear all chat history button from menu
- Enabled when not generating
> fix: Disabling the clear all history button when loading

- ClientAdvisor/App/app.py
Bug- 7289-[Internal-QA] - An error occurs after asking 2-3 questions.
Note:- As I was unable to reproduce the bug through various questions, but I can consistently reproduce it by clicking the "Stop Generating" button, which is expected behavior. Additionally, adding an extra line to a question also triggers the bug. To address this, I have resolved the issue by removing leading and trailing whitespace characters from the query. 
**Before Fix**: 
**After Fix**: (Ask question with adding new line and check the response)
> fix: Added strip functionalities to remove leading and trailing whitespace characters from a "query" string.

- ClientAdvisor/AzureFunction/function_app.py
In existing system prompts one prompt causing to give karen berg for all example question
Previous behavior
After updating prompt
> Fix 7548: Karen berg name issue resolved when asked example questions

- ClientAdvisor/App/frontend/src/components/Cards/Cards.module.css
- ClientAdvisor/App/frontend/src/components/UserCard/UserCard.tsx
- ClientAdvisor/App/frontend/src/pages/layout/Layout.module.css
- ClientAdvisor/App/frontend/src/pages/layout/Layout.tsx
bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/7881
Steps to reproduce:
**1. Automated checks**
Title: WCAG 2.1.1: Ensure elements that have scrollable content are accessible by keyboard (._cardsColumn_abkbw_115)
Tags: Accessibility, WCAG 2.1.1, scrollable-region-focusable
Issue: Ensure elements that have scrollable content are accessible by keyboard (scrollable-region-focusable - https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable)
Target application: Woodgrove Bank - https://caka-app-service.azurewebsites.net/
Element path: ._cardsColumn_abkbw_115
Snippet: <div class="_cardsColumn_abkbw_115">
**2. Keyboard: Tab checks**
Open BYOc - Client Advisor URL
Click on tab in keyboard, so that, it needs to traverse to all section and options but …
> fix:  Accessibility default Screen

- ClientAdvisor/App/app.py
- ClientAdvisor/App/tests/backend/auth/test_auth.py
- ClientAdvisor/App/tests/backend/history/test_cosmosdb_service.py
- ClientAdvisor/App/tests/backend/test_utils.py
- ClientAdvisor/App/tests/test_app.py
- ClientAdvisor/App/tools/data_collection.py
> perf: Linting fixes

- ClientAdvisor/README.md
- README.md
- ResearchAssistant/README.md
- TRANSPARENCY_FAQ.md
* Updated the text in the docs
* ...
> docs: Psl readmeupdate for Azure Open AI -> OpenAI

- ClientAdvisor/AzureFunction/requirements.txt
* The purpose of downgrading the Semantic Kernel version in the requirements.txt file is to ensure compatibility and stability of the Azure Function app, as certain versions may introduce issues preventing proper execution. This action aims to resolve intermittent errors experienced when using the latest version of the Semantic Kernel.
- Verify if the function app starts without errors after the downgrade.
- Confirm that all dependencies are properly installed post-downgrade.
- Test the key functionality of the app to ensure it works as expected.
- Monitor for any recurring errors that might indicate further issues with the downgrade.
> fix: Downgrade Semantic Kernel Version for Azure Function Compatibility

- .github/workflows/test_research_assistant.yml
- ResearchAssistant/App/test_app.py
- ResearchAssistant/Deployment/scripts/aihub_scripts/requirements.txt
* ...
Writing unit test case for Research Assistant Backend
> test: Research assistant backend unit test

- ClientAdvisor/App/frontend/src/api/api.ts
This pull request includes changes to the `ClientAdvisor/App/frontend/src/api/api.ts` file to add a new utility function and improve error handling in the `historyUpdate` function. The most important changes are:
Enhancements to error handling and utility functions:
* Added a new utility function `isLastObjectNotEmpty` to check if the last object in an array is not empty. This function is used to handle cases where the array might be empty or the last object in the array is empty.
* Updated the `historyUpdate` function to use the `isLastObjectNotEmpty` utility function to determine whether to proceed with the update or return an error response. If the last object in the `messages` array is empty, the function now returns a `500 Internal Server Error` response.
- [X ] No
Verify that the …
> fix: update history method changes

- .github/workflows/RAdeploy.yml
- .github/workflows/build-docker.yml
- ResearchAssistant/Deployment/scripts/checkquota.sh
* ...
This pull request introduces a new quota check mechanism in the deployment workflow to ensure sufficient resources are available before proceeding with the deployment. The most important changes include adding a quota check script, updating the deployment region based on quota availability, and handling quota check failures by sending notifications and failing the pipeline if necessary.
Quota check implementation:
* [`.github/workflows/RAdeploy.yml`](diffhunk://#diff-752e6c51411766596494ef842fac2f6094759426c2db70f0d665943a9438cb2eR19-R57): Added steps to run a quota check script, send a notification if the quota check fails, and fail the pipeline if necessary. [[1]](diffhunk://#diff-752e6c51411766596494ef842fac2f6094759426c2db70f0d665943a9438cb2eR19-R57) …
> ci: implement quota check in CI Pipeline to ensure resource availability in supported region for RA

- .github/workflows/CAdeploy.yml
- ClientAdvisor/Deployment/scripts/checkquota.sh
Add the variable **AZURE_REGIONS_CA** with the value: northcentralus
* ...
This pull request includes changes to the deployment scripts and workflow configuration to support dynamic Azure regions. The most important changes include adding a new environment variable for Azure regions and updating the quota check script to utilize this variable.
**Workflow Configuration:**
* [`.github/workflows/CAdeploy.yml`](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468R29): Added `AZURE_REGIONS` environment variable to the workflow configuration to dynamically set Azure regions.
**Deployment Script Updates:**
* [`ClientAdvisor/Deployment/scripts/checkquota.sh`](diffhunk://#diff-e3ea3e461b5c0db697cd4f2033aa552f7d9756b8d01046028834a55aa4c1775bL4-R4): Updated the script to …
> fix: quota check script with dynamic region handling

- ClientAdvisor/App/frontend/src/pages/chat/Chat.tsx
* This pull request includes a significant change to the `ClientAdvisor/App/frontend/src/pages/chat/Chat.tsx` file. The change primarily addresses the handling of null object responses from the History Generate Method to improve error handling and user experience.
Error handling improvement:
* Added a check for the first read operation to handle cases where the response is `undefined`. If this condition is met, a default error message is created and processed to inform the user about the issue, and metadata for the conversation history is generated.
* ...
> fix: Fixed bug 14071 to handle null object error in history generate method

- ResearchAssistant/Deployment/scripts/aihub_scripts/create_ai_hub.py
This approach first starts the asynchronous hub creation process, waits for a short period to ensure the hub has time to be created, and then retrieves the hub details to confirm its successful creation. This sequence ensures the proper handling of the hub creation workflow in the system.
* ...
> fix: Fix for Handling Hub Creation and Validation in Azure ML Client

- ResearchAssistant/Deployment/scripts/aihub_scripts/create_ai_hub.py
- ResearchAssistant/Deployment/scripts/aihub_scripts/requirements.txt
This commit upgrades the `azure-ai-ml` package to version 1.26.1 and restores the script to its base version without any asynchronous workarounds. The upgrade ensures compatibility with the latest features and improvements in the `azure-ai-ml` package while maintaining a simpler, more stable script configuration.
Key Changes:
- Upgraded `azure-ai-ml` package to version 1.26.1.
- Restored script to base version, removing asynchronous workarounds.
- Ensured compatibility with new package version and streamlined deployment process.
This update provides improved functionality with the latest package version while ensuring stability and ease of use in the deployment process.
* ...
> fix: Upgrade azure-ai-ml Package to Version 1.26.1 and Restore Script to Base Version

- ClientAdvisor/App/frontend/src/components/ChatHistory/ChatHistoryListItemCell.test.tsx
- ClientAdvisor/App/frontend/src/components/ChatHistory/ChatHistoryListItemCell.tsx
This pull request includes several changes to the `ChatHistoryListItemCell` component and its tests to improve the user interface and testing accuracy. The most important changes include updating the test cases to check for multiple elements, modifying the title truncation logic, and adding a tooltip for better user experience.
* [`ClientAdvisor/App/frontend/src/components/ChatHistory/ChatHistoryListItemCell.test.tsx`](diffhunk://#diff-7cde97d686efa7a853f4865b347a15f3a825ce8e06fad55fce3f2a1aeb03587cL41-R42): Updated the test case to check for multiple elements with the same text using `getAllByText` instead of `getByText`.
* [`ClientAdvisor/App/frontend/src/components/ChatHistory/ChatHistoryListItemCell.test.tsx`](diffhunk://#diff-7cde97d686efa7a853f4865b347a15f3a825ce8e06fad55fce3f2a1aeb0 …
> fix: Client Advisor- After hovering over the chat history, no tooltip is displayed

- .github/workflows/CAdeploy.yml
This GitHub Actions pipeline step generates a unique resource group name using a specified account name (cabyoc) combined with a shortened UUID. The pipeline prints a message indicating the start of the generation process, then creates the resource group name in the format arg-{ACCL_NAME}-{UUID}. 
The generated name is saved as an environment variable (RESOURCE_GROUP_NAME) to be used in later pipeline steps, and it also prints the generated name to the log for visibility.
* ...
> ci: GitHub Actions Pipeline - Generate Unique Resource Group Name

- ClientAdvisor/App/WebApp.Dockerfile
- ResearchAssistant/App/WebApp.Dockerfile
* This pull request includes updates to the Dockerfiles for both `ClientAdvisor` and `ResearchAssistant` applications to improve the package installation process. The main changes involve upgrading pip, setuptools, and wheel before installing the required packages.
Dockerfile updates:
* [`ClientAdvisor/App/WebApp.Dockerfile`](diffhunk://#diff-20f4a397b3c9e95c0d9ff645f204072ccf269a46885b619cf28977978cde58fbL25-R26): Added commands to upgrade pip, setuptools, and wheel before installing the requirements from `requirements.txt`.
* [`ResearchAssistant/App/WebApp.Dockerfile`](diffhunk://#diff-fdb1c0c03bd95143bb908767b12e5fc6c27a89952e5232ac7c65a2b4f5d79386L24-R25): Added commands to upgrade pip, setuptools, and wheel before installing the requirements from `requirements.txt`.
Verify that the …
> fix: Updates to the Dockerfiles for both `ClientAdvisor` and `ResearchAssistant` 

- src/AzureFunction/function_app.py
This change dynamically replaces the placeholder `{SelectedClientName}` in `HOST_INSTRUCTIONS` with the actual selected client's name. 
This ensures all prompts and generated responses from Azure OpenAI are correctly contextualized, consistent, and specifically tailored to the currently selected client.
* ...
> fix: Inject dynamic client name into Azure OpenAI host instructions

- ClientAdvisor/Deployment/scripts/fabric_scripts/requirements.txt
- ClientAdvisor/Deployment/scripts/fabric_scripts/run_fabric_items_scripts.sh
This pull request includes updates to the `requirements.txt` file and a script used for deployment. The changes primarily focus on adding a new package dependency and modifying the installation command for Python packages.
Dependency updates:
* [`ClientAdvisor/Deployment/scripts/fabric_scripts/requirements.txt`](diffhunk://#diff-78c9a13865a79613ee2817e5ca2748360d40c2a4eb869841ac6a53d814d2724fR5): Added the `packaging` library to the list of required packages.
Script improvements:
* [`ClientAdvisor/Deployment/scripts/fabric_scripts/run_fabric_items_scripts.sh`](diffhunk://#diff-005e83a3715c4b2f87634aecef960d4f2e3da09714204fc395f775144e2443c4L48-R48): Modified the `pip install` command to include the `--user` flag, ensuring that packages are installed in the user’s site-packages directory.
> fix: pip package issue

- .github/workflows/CAdeploy.yml
- .github/workflows/Create-Release.yml
- .github/workflows/azure-dev-validation.yml
* This pull request includes updates to GitHub Actions workflows to improve security and streamline triggers. The most important changes involve updating the token used for authentication and modifying the trigger conditions for a specific workflow.
Security improvement:
* [`.github/workflows/Create-Release.yml`](diffhunk://#diff-c109ec8314de1a4577b4ae4cfb1ca97dcbf8748d46e6b53d282e95af921de5c6L59-R59): Updated the `GITHUB_TOKEN` environment variable to use `secrets.GITHUB_TOKEN` instead of `secrets.TOKEN`, ensuring alignment with standard GitHub practices for secure token management.
Trigger condition simplification:
* [`.github/workflows/azure-dev-validation.yml`](diffhunk://#diff-1dcfea15147980582b28c1b2c1b66b9841f315f12f68b855d8bc72f08aaa09d1L3-L6): Removed the `push` event trigger for …
> fix:  updates to GitHub Actions workflows to improve security and streamline triggers

- .devcontainer/setup_env.sh
- .github/workflows/CAdeploy.yml
- .gitignore
- README.md
- infra/scripts/add_user_scripts/create_sql_user_and_role.sh
- infra/scripts/index_scripts/create_sql_tables.py
- infra/scripts/index_scripts/requirements.txt
- infra/scripts/run_create_index_scripts.sh
This pull request includes updates to improve script compatibility, streamline dependencies, and adjust deployment configurations. The most important changes involve enhancing script execution logic, removing unused dependencies, and updating deployment parameters.
* [`.devcontainer/setup_env.sh`](diffhunk://#diff-884be0103962fdae0355a22edc0c050cf6051ef4952a1df7d2a9bff7a0d73ed6L7-R7): Updated the `chmod` command to use `sudo` for better compatibility across environments. Removed installation steps for Azure Functions Core Tools, as it is no longer required. [[1]](diffhunk://#diff-884be0103962fdae0355a22edc0c050cf6051ef4952a1df7d2a9bff7a0d73ed6L7-R7) [[2]](diffhunk://#diff-884be0103962fdae0355a22edc0c050cf6051ef4952a1df7d2a9bff7a0d73ed6L23-L28)
* …
> fix: minor fixes in setup_env.sh, create_sql_user_role.sh, readme

- .github/workflows/CAdeploy.yml
- infra/scripts/checkquota.sh
- infra/scripts/index_scripts/create_search_index.py
This pull request includes updates to the `infra/scripts` directory, addressing changes to model definitions and script functionality. The most important changes involve updating model identifiers in a quota-checking script and removing an unnecessary delay in the indexing script.
* [`infra/scripts/checkquota.sh`](diffhunk://#diff-48664f6f17fa7d234fba297bb48df87fb6dbde30ca96e565929418b768e32d5dL35-R35): Updated the model identifier from `OpenAI.Standard.gpt-4` to `OpenAI.GlobalStandard.gpt-4o-mini` in the `MIN_CAPACITY` mapping to reflect the latest naming conventions or requirements.
* [`infra/scripts/index_scripts/create_search_index.py`](diffhunk://#diff-0173dadda6396f72ef6065aa23a8d5f37b98561524a6aa23363f31a35b29a4e1L262): Removed an unnecessary `time.sleep(4)` call, likely to improve …
> fix: Update model in checkquota.sh and remove unnecessary sleep

- .dockerignore
- src/WebApp.dockerignore
- This PR adds a ".dockerignore" file to prevent unnecessary files and directories (such as virtual environments, build artifacts, logs, node_modules, and IDE configs) from being sent to the Docker daemon during image builds.
- Optimizing the build context improves performance and reduces image size and build time.
Verify that the following are valid:
- Confirm .dockerignore is present at root directory.
- Ensure expected files (e.g. .git, node_modules, __pycache__, etc.) are excluded from build context.
- Run a Docker build and verify only necessary files are included.
> build: Add .dockerignore to optimize Docker build context

- infra/deploy_ai_foundry.bicep
- infra/deploy_app_service.bicep
- infra/main.bicep
- infra/main.json
- src/App/app.py
- src/App/backend/event_utils.py
- src/App/requirements.txt
This pull request introduces several changes to enhance telemetry, streamline configuration, and update dependencies across the infrastructure and application code. The key updates include enabling Application Insights integration, adding telemetry tracking for critical events, and updating API versions for Azure services. Below is a categorized summary of the most important changes:
* Integrated Application Insights into the application by adding a connection string parameter, configuring the monitor, and logging relevant events. (`infra/deploy_ai_foundry.bicep`, `infra/deploy_app_service.bicep`, `src/App/app.py`) [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626R495-R496) [[2]](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50 …
> feat: added opentelemetry log

- infra/deploy_sql_db.bicep
- infra/main.json
* ...
This pull request introduces updates to the infrastructure deployment scripts, focusing on enhancing security, upgrading dependencies, and improving compatibility with newer API versions. The most significant changes include enforcing a minimum TLS version for SQL servers, upgrading the Bicep CLI version, and transitioning to a newer API version for Azure Cognitive Services.
* Enforced a minimum TLS version of `1.2` for SQL servers in both `infra/deploy_sql_db.bicep` and `infra/main.json` to improve security. [[1]](diffhunk://#diff-ad1f5ffce550be5519a4bdad9aa20bcf05b0a0657794e1ac1bc4bd271f1068e0R32) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4R1991)
* Upgraded the Bicep CLI version from `0.34.44.8038` to `0.35.1.17967` across multiple …
> fix: update minimal tls version

- .github/dependabot.yml
- .github/workflows/scheduled-Dependabot-PRs-Auto-Merge.yml
* Introduced a scheduled GitHub Actions workflow to auto-approve and auto-merge Dependabot PRs targeting the dependabotchanges branch.
* Also optimized the dependabot.yml configuration to group dependency updates by ecosystem and path, significantly reducing PR noise.
* Enhanced rebase logic to handle merge conflicts using --strategy-option=theirs.
* Implemented multi-strategy auto-merge (merge, squash, rebase) with fallback handling.
* Improved overall script reliability and compatibility with repo-level merge restrictions.
* ...
> chore: Updated Dependabot config to group PRs and added workflow for scheduled auto-merge

- docs/CustomizingAzdParameters.md
- docs/DeploymentGuide.md
- infra/deploy_ai_foundry.bicep
- infra/main.bicep
- infra/main.bicepparam
This pull request introduces support for reusing an existing Log Analytics Workspace during deployment. The changes span documentation updates, infrastructure configuration adjustments, and parameter additions to enable this functionality.
* [`docs/CustomizingAzdParameters.md`](diffhunk://#diff-6eec6ba43f4d3beb5835ad60e22b6974f1224c7b5ff024f690cd9549e8b4aec7R44-R48): Added instructions for setting the `AZURE_ENV_LOG_ANALYTICS_WORKSPACE_ID` environment variable to reuse an existing Log Analytics Workspace.
* [`docs/DeploymentGuide.md`](diffhunk://#diff-5a9feaaa3fe70489e88e08725db341b9dafb6a4185d382bba81c4093aaaded7cR117-R118): Updated the deployment guide to include a new parameter for specifying an existing Log Analytics Workspace ID.
* …
> feat: EXP environment changes for Log Analytics workspace

- infra/bicep/deploy_keyvault.bicep
- infra/bicep/main.bicep
- infra/bicep/main.json
This pull request makes several updates to the Key Vault configuration in the Bicep templates and JSON files, focusing on enabling soft delete, modifying retention policies, and removing purge protection. Additionally, it updates the Bicep compiler version and adjusts metadata. Below is a summary of the key changes:
* Changed the `enableSoftDelete` parameter default value to `true` and updated the retention period for soft delete to 7 days instead of 30 days in `infra/bicep/deploy_keyvault.bicep` and `infra/bicep/main.json`. (`[[1]](diffhunk://#diff-62e03f5aa97a09f01ea1acc8ad346eb5d59a3ef4947759dd21e0f0c3d2fbc2eaL32-R42)`, `[[2]](diffhunk://#diff-a9c0ff862c2ddf7d893af29e946199ace2a134f3d51fa3071e6e35a7b0b6c0b2L1048-R1048)`)
* Removed the `enablePurgeProtection` parameter and its …
> fix: researcher - enabling soft delete and removing purge protection for key vault

- .github/workflows/CAdeploy.yml
This pull request updates the `.github/workflows/CAdeploy.yml` file to enhance the notification process for deployment failures. The main improvement is the addition of a more detailed and structured email body for failure notifications.
* Enhanced the email body to include a detailed message with a personalized introduction, a description of the issue, the build URL, and a request for investigation. This replaces the previous minimalistic message.
* ...
* ...
> ci: enhance deployment failure email notifications in CAdeploy workflow

- .github/workflows/CAdeploy.yml
- .github/workflows/test_automation.yml
This pull request updates the deployment and test automation workflows in the `.github/workflows` directory to enhance flexibility, improve resource management, and streamline automation processes. The most significant changes include adding branch support for deployment triggers, using environment variables for resource capacities, refining deployment tagging, and removing redundant role assignments.
* **Branch Trigger Updates**: Added support for `dev` and `demo` branches in addition to `main` for triggering deployments.
* **Environment Variable Integration**: Updated `GPT_MIN_CAPACITY` and `TEXT_EMBEDDING_MIN_CAPACITY` to use environment variables instead of hardcoded values for better configurability.
* **Improved Deployment Tagging**: Refined the logic for image tagging by replacing …
> ci: fix client advisor deploy and test automation workflows

- infra/bicep/main.bicep
- infra/bicep/main.json
This pull request introduces a new resource group tag for better resource organization and updates metadata in the `infra/bicep` files to reflect a newer version of the Bicep generator. The changes also include a minor update to the chatbot's system message formatting.
* Added a new resource group tag, `templateName: Research Assistant`, in `infra/bicep/main.bicep` and its corresponding JSON template. This tag helps identify resources associated with the Research Assistant solution. [[1]](diffhunk://#diff-6d5bbaf49aff20fcd5df30e6b6780f53182fdf8f71e8c25950e24d94d50e2612R19-R28) [[2]](diffhunk://#diff-a9c0ff862c2ddf7d893af29e946199ace2a134f3d51fa3071e6e35a7b0b6c0b2R257-R266)
* Updated the Bicep generator version from `0.36.1.42791` to `0.36.177.2456` and changed the associated …
> feat: Added templateName tag on rg

- .github/workflows/CAdeploy.yml
- docs/QuotaCheck.md
- infra/scripts/quota_check_params.sh
* ...
This pull request updates default model capacities and environment variables to align with new requirements for resource allocation. The most significant changes include increasing the capacity for `gpt-4o-mini` and adjusting related documentation and scripts accordingly.
* [`.github/workflows/CAdeploy.yml`](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468L13-R14): Reduced `GPT_MIN_CAPACITY` from 250 to 200 and increased `TEXT_EMBEDDING_MIN_CAPACITY` from 40 to 80 in the workflow environment variables.
* [`infra/scripts/quota_check_params.sh`](diffhunk://#diff-686f17dd7cf7e8af9b5575a7098de6011c9bc4b0cdc7aa3c631b66b0d5fe6975L50-R50): Updated `DEFAULT_MODEL_CAPACITY` to set `gpt-4o-mini` capacity to 200 (previously 30) while keeping …
> fix: updated model capacity minimum to 200

- infra/scripts/copy_kb_files.sh
This pull request improves the retry mechanism for uploading files to Azure Blob Storage in the `infra/scripts/copy_kb_files.sh` script. The changes increase the maximum retry attempts, enhance logging for better visibility, and refine the retry logic to handle failures more effectively.
Enhancements to retry mechanism:
* Increased the maximum number of retry attempts from 3 to 5 for uploading files to Azure Blob Storage. (`maxRetries` variable added and used consistently)
* Improved logging to include the current attempt number and the total number of retries, along with the wait time before the next retry.
* Updated retry logic to double the sleep time between attempts and added a final error message if all retry attempts fail.
* ...
> fix: Increase retry attempts and improve error messaging for file upload script

- infra/bicep/deploy_azure_open_ai.bicep
- infra/bicep/main.json
- infra/scripts/checkquota.sh
- infra/scripts/quota_check_params.sh
* ...
This pull request updates the Azure OpenAI resource configuration and associated scripts to reflect a change in the SKU naming convention from `Standard` to `GlobalStandard`. Additionally, template hashes in the `main.json` file have been updated to align with the changes. Below is a summary of the most important changes:
* Changed the SKU name for `text-embedding-ada-002` from `Standard` to `GlobalStandard` in `infra/bicep/deploy_azure_open_ai.bicep` and `infra/bicep/main.json`. This ensures consistency with the updated naming convention. [[1]](diffhunk://#diff-a0956e4d5b20c29bc146772ad4a59ade4da5e130db3a8495ac8f26b50c29eb87L50-R50) [[2]](diffhunk://#diff-a9c0ff862c2ddf7d893af29e946199ace2a134f3d51fa3071e6e35a7b0b6c0b2L783-R783)
* Updated the `MIN_CAPACITY` mapping in …
> chore: migrate model type to global standard

- src/App/backend/services/sqldb_service.py
- src/App/frontend/src/api/api.ts
This pull request introduces retry mechanisms with exponential backoff and timeout handling for database connections in the backend and API calls in the frontend. These changes aim to improve the resilience of the application by handling transient failures more gracefully.
* `src/App/backend/services/sqldb_service.py`:
- Added a retry mechanism with exponential backoff for the `get_connection` function, allowing up to 5 attempts with an initial delay of 2 seconds between retries. The delay doubles with each failed attempt. [[1]](diffhunk://#diff-42f37b2f18081a3a44cc215ed72549048a3265376381ca1bdadc1fc6edd4f33eR38-R41) [[2]](diffhunk://#diff-42f37b2f18081a3a44cc215ed72549048a3265376381ca1bdadc1fc6edd4f33eR63-R78)
- Imported the `time` module to enable the use of `time.sleep` for retry …
> fix: Implement retry logic for database connection and user fetching

- src/App/app.py
- src/App/backend/agents/agent_factory.py
- src/App/backend/plugins/chat_with_data_plugin.py
- src/App/tests/backend/plugins/test_chat_with_data_plugin.py
This pull request introduces significant updates to the application's agent management and logging mechanisms, as well as improvements to SQL query handling and error management. The changes primarily focus on adding support for a new SQL agent, enhancing logging for debugging purposes, and improving cleanup processes during application shutdown and agent deletion.
* [`src/App/app.py`](diffhunk://#diff-03cd2a13f881a9c3ca81c2cf109cb722585617374d60e38118ebe473a2e98da0L84-R102): Added initialization and cleanup logic for a new SQL agent during application startup and shutdown. Improved error handling and logging during the shutdown process to ensure agents are properly cleaned up.
* [`src/App/backend/agents/agent_factory.py`](diffhunk://#diff-ceceeaf6b7bac47e276ae594ac9d58cb0c2de4198350caa13c …
> feat: working agent management

- .github/dependabot.yml
This pull request updates the configuration for Dependabot to reflect new locations for Python script directories. The changes ensure that dependency updates are tracked in the correct locations after a directory restructuring.
Configuration updates:
* Updated the `directory` path for Fabric Scripts from `/src/infra/scripts/fabric_scripts` to `/infra/scripts/fabric_scripts` in `.github/dependabot.yml`.
* Updated the `directory` path for Index Scripts from `/src/infra/scripts/index_scripts` to `/infra/scripts/index_scripts` in `.github/dependabot.yml`.
> chore: directory update in dependabot template

- .github/dependabot.yml
- infra/main.bicep
This pull request updates the configuration for Dependabot to reflect recent changes in the project directory structure. Specifically, it corrects the paths for Python dependencies managed in the infrastructure scripts, ensuring that Dependabot monitors the correct locations for updates.
Configuration updates for directory structure:
* Updated the `directory` paths in `.github/dependabot.yml` for Fabric Scripts and Index Scripts from `/src/infra/scripts/...` to `/infra/scripts/...` to match the current project layout. [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L34-R34) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L48-R48)
> chore: down merging main into dev

- docs/LocalSetupGuide.md
* This pull request adds a new local development guide to the project documentation. The guide provides step-by-step instructions for setting up the application locally, including environment requirements, configuration, and running the app.
Documentation improvements:
* Added a new `LocalSetupGuide.md` file with detailed instructions for setting up the development environment, configuring environment variables, using a Python virtual environment, and starting the application locally.
* ...
> docs: added readme for local setup

- infra/main.bicep
- src/App/backend/agents/agent_factory.py
This pull request introduces improvements to asset value query instructions, adds a new `createdBy` parameter for resource tagging, and makes a minor documentation correction. The changes enhance clarity and traceability in both infrastructure deployment and SQL query generation.
**Asset value query logic improvements:**
* The instructions for generating T-SQL queries in both `infra/main.bicep` and `src/App/backend/agents/agent_factory.py` have been clarified. The guidance now explicitly states to always return the SUM of the latest investments for total asset value questions, and to return all latest investments without summing for current asset/investment value questions. This helps ensure more accurate and consistent query responses. …
> fix: Return consistent response for 'what is the asset value' query.

- infra/main.bicep
- infra/main.json
This pull request updates the infrastructure templates to improve support for deploying with either new or existing AI Foundry projects, and adds outputs to expose the System Assigned Managed Identity Principal Id. It also updates the way container image tags are specified and referenced. The most important changes are as follows:
**AI Foundry Project Integration Improvements:**
* Enhanced support for existing AI Foundry projects by extracting subscription ID, resource group, and service name from the `existingFoundryProjectResourceId` parameter, and referencing the existing project resource directly in the deployment. [[1]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L30307-R30328) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edc …
> refactor: Update container image tag to include version detail

- .github/workflows/CAdeploy.yml
This pull request makes a minor update to the deployment workflow configuration. The most notable change is a parameter name correction in the Azure deployment step to ensure the correct value is passed.
* Deployment workflow fix:
* [`.github/workflows/CAdeploy.yml`](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468L147-R147): Changed the parameter name from `containerImageTag` to `imageTag` in the Azure deployment command to match expected input.
* ...
> ci: fix deploy pipeline

- infra/main.bicep
- infra/scripts/process_sample_data.sh
- src/App/backend/common/config.py
- src/App/backend/services/sqldb_service.py
This pull request introduces a dedicated user-assigned managed identity for SQL database operations with limited permissions, separating it from the web app's managed identity. The infrastructure, environment outputs, deployment scripts, and backend code are updated to consistently use this new SQL-specific identity for database access, improving security and permission scoping. Additionally, minor improvements are made to resource naming and redundancy settings.
**Managed Identity Separation and Security Improvements:**
* Added a new `sqlUserAssignedIdentity` resource in `infra/main.bicep` to serve as a dedicated managed identity for SQL operations, with limited permissions (`db_datareader`, `db_datawriter`).
* Updated the Key Vault access policy to grant the new SQL managed identity the …
> feat: Create Separate User Assigned Identity for SQL DB with Specified Access

- .github/workflows/CAdeploy.yml
This pull request updates the workflow environment variable assignments in `.github/workflows/CAdeploy.yml` to use the SQL managed identity values instead of the web app managed identity values for `CLIENT_ID` and `CLIENT_NAME`.
Environment variable assignment updates:
* Changed the source for `CLIENT_ID` and `CLIENT_NAME` to use `.managedidentitY_SQL_CLIENTID.value` and `.managedidentitY_SQL_NAME.value` respectively, instead of the previous web app values.
* ...
> ci: Fix deploy workflow
