microsoft/Build-your-own-copilot-Solution-Accelerator

- Deployment/scripts/aihub_scripts/requirements.txt
- Deployment/scripts/index_scripts/create_articles_index.py
Downgraded - azure-ai-ml from 1.16 to 15.0
> ai-hub-version downgraded

- App/frontend/src/components/Homepage/Cards.tsx
- App/frontend/src/components/QuestionInput/QuestionInput.tsx
- App/frontend/src/components/SidebarView/SidebarView.tsx
- App/frontend/src/pages/Homepage/Homepage.module.css
- App/frontend/src/pages/layout/Layout.module.css
- App/frontend/src/pages/layout/Layout.tsx
**Bug**: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4420
**1. Automated check: Label**
Issue: Form elements must have labels (label - https://accessibilityinsights.io/info-examples/web/label)
**2. Automated check: button-name**
Issue: Buttons must have discernible text (button-name - https://accessibilityinsights.io/info-examples/web/button-name)
**3. Images**
Open BYOAI URL.
Open inspect.
Alternative text for Images.
Expected result: Need to add an alternative text for image.
> fix: [Bug-4420] [Landing Page] Added accessbility changes

- App/frontend/src/components/DraftDocumentsView/DraftDocumentsView.module.css
- App/frontend/src/components/DraftDocumentsView/DraftDocumentsView.tsx
- App/frontend/src/components/SidebarView/SidebarView.tsx
- App/frontend/src/pages/layout/Layout.tsx
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4475
**Automated checks: Label**
Title: WCAG 4.1.2: Form elements must have labels (#TextField5)
Tags: Accessibility, WCAG 4.1.2, label
Issue: Form elements must have labels (label - https://accessibilityinsights.io/info-examples/web/label)
> Fix: [Bug 4475] [Draft Page] Added accessibility changes

- App/frontend/src/components/Answer/Answer.module.css
- App/frontend/src/components/SidebarView/GrantView/GrantView.tsx
- App/frontend/src/components/SidebarView/SidebarView.module.css
- App/frontend/src/pages/chat/Chat.module.css
Bug :  https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/4443
High Contrast modes
Open BYOAI URL.
Go to system setting ->Accessibility->Contrast themes->select aquatic in drop down-> apply.
Go to BYOAI URL, you can find the screen, outer border is not visible
Expected result: By providing borders to the fields.
> fix: [Bug-4443] [Grants]color constrat css changes added

- Deployment/scripts/aihub_scripts/create_ai_hub.py
- Deployment/scripts/aihub_scripts/requirements.txt
Update the below package 
- azure-ai-ml -> 1.17.1
Updated the create_ai_hub script to support the latest changes on the package.
> PSL | Grant Writer | azure-ai-ml package update & Create_ai_hub script update

- Deployment/scripts/aihub_scripts/create_ai_hub.py
AI_Search endpoint updated to correct value.
target = f"https://{ai_search_res_name}.search.windows.net/"
> ai_hub_deployment issue fixed during prompt flow deployment

- Deployment/scripts/aihub_scripts/create_ai_hub.py
Updated the API Version for AI Search while executing ai_hub script.
> Update create_ai_hub.py for AI Search API Version

- ResearchAssistant/Deployment/AIStudioDeployment.md
- ResearchAssistant/Deployment/FabricDeployment.md
- ResearchAssistant/Deployment/PromptFlowEvaluation.md
- ResearchAssistant/Deployment/PromptFlowSafetyEvaluation.md
- ResearchAssistant/Deployment/bicep/deploy_aihub_scripts.bicep
- ResearchAssistant/Deployment/bicep/deploy_fabric_scripts.bicep
- ResearchAssistant/Deployment/bicep/deploy_index_scripts.bicep
- ResearchAssistant/Deployment/bicep/deploy_upload_files_script.bicep
- ResearchAssistant/Deployment/bicep/main.json
- ResearchAssistant/Deployment/scripts/copy_kb_files.sh
- ResearchAssistant/Deployment/scripts/run_create_aihub_scripts.sh
- ResearchAssistant/Deployment/scripts/run_create_index_scripts.sh
- ResearchAssistant/Deployment/scripts/run_fabric_items_scripts.sh
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/3946/
As we were getting below errors while doing the deployment, so we have changed the URL's and file paths everywhere in this accelerator as per the new folder structure that recently got added.
> fix: Updated the URL's and file path as per the current folder structure

- ClientAdvisor/Deployment/scripts/create_azure_functions.sh
Added timeout in create azure function script.
> added timeout in azure function script

- ClientAdvisor/App/app.py
Time format is changed 24Hrs format and Asset value is display as sum of all investments over full duration.
Below is the screenshot for reference:
> Fix for time format and asset value on UI 

- ClientAdvisor/App/frontend/src/pages/layout/Layout.module.css
Bug: https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/6968
**Accessibility**: Color contrast - adjust the background pill color and styling to be ADA friendly in BYOc-Client Advisor.
> fix: changed backgound color and color of the text of client selected

- ClientAdvisor/AzureFunction/function_app.py
Resolve inconsistencies in portfolio value reporting based on query type.
> Fix: Clarify Portfolio Value Calculation Instructions

- ClientAdvisor/AzureFunction/function_app.py
Bug 5663 - Chatbot recommends 10 questions to me, but only 4 give accurate responses.
**Before fix**: (Getting inaccurate and inconsistent responses for below list of questions)
**After Fix**: (Getting accurate and consistent responses for below list of questions)
> fix: Added the system message to ensure consistent and accurate data retrieval for the list of questions.

- ClientAdvisor/AzureFunction/function_app.py
Fixed the issue for Client ID is displaying in response 
[Bug 7874](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/7874): [Internal QA]-Bug - Client ID is displaying in response
> Fixed the issue for Client ID is displaying in response 

- ClientAdvisor/AzureFunction/function_app.py
- ClientAdvisor/Deployment/bicep/main.bicep
- ClientAdvisor/Deployment/bicep/main.json
**Bug - 7953**: [Internal QA] -BYOc_CA-Bug - Chatbot recommends 10 questions but 1 give inaccurate response
**Before Fix:** (Getting the response like "I cannot answer this question from the data available. Please rephrase or add more details.")
**After Fix:** (Getting proper response)
> fix: Modified the system message to fetch the action items from the previous meeting with the client and upgraded the open AI API Version

- ClientAdvisor/App/app.py
- ClientAdvisor/AzureFunction/function_app.py
We are reverting the system prompts which are added for the bug fixing by PSL team.
Keeping the changes from the below mentioned date in screenshot
Function App:
App.py:
Will keep those changes as backup in dev branch.
> fix: Reverted app & function app codes done by psl

- ResearchAssistant/App/WebApp.Dockerfile
Update WebApp.Dockerfile for Research assistant
> Update WebApp.Dockerfile for Research assistant

- ClientAdvisor/App/app.py
> code updated to test

- ClientAdvisor/App/app.py
- ClientAdvisor/App/requirements-dev.txt
- ClientAdvisor/App/requirements.txt
package update for openai and httpx.
> pakcage update for openai and httpx

- .github/PULL_REQUEST_TEMPLATE.md
Raising PR to Merge the template in main Branch.
Previously it was on Roopan's fork Branch .
> Template-Main-Branch-PR

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/subtask.md
- .github/workflows/stale-bot.yml
*  The purpose of these changes is to improve repository management by standardizing issue submissions and managing inactive issues and pull requests
1. **Issue Template**: Confirm the issue template is correctly set up and auto-populates when creating new issues.
2. **StaleBot**: Confirm that stale issues and PRs are identified and commented on, and that inactive ones are closed after the specified period.
> feat: Added Issue Template and StaleBot for Repository Management

- .github/workflows/pylint.yml
- ClientAdvisor/App/.flake8
- ClientAdvisor/App/.pylintrc
- ClientAdvisor/App/requirements.txt
- ResearchAssistant/App/.flake8
- ResearchAssistant/App/.pylintrc
- ResearchAssistant/App/requirements.txt
* ...I have successfully implemented Pylint for both the Client Advisor and Research Assistant projects, ensuring code quality and consistency across the codebase. 
* The configuration includes a custom .pylintrc file tailored to address project-specific requirements, such as line length, variable naming conventions, and ignoring certain warnings that are not relevant to the project. 
* Additionally, the configuration is flexible and can be modified in the future to accommodate evolving project requirements, ensuring adaptability while maintaining high coding standards.
* ...
> feat: Pipeline

- ResearchAssistant/Deployment/scripts/aihub_scripts/requirements.txt
* This PR downgrades the "azure-ai-ml" package to version 1.17.1 to resolve version conflicts that were causing deployment failures related to AI Hub scripts.
1. Verify that the package version downgrade to 1.17.1 is applied successfully.
2. Test the deployment process to ensure the issue with AI Hub scripts failing due to package conflicts is resolved.
3. Ensure that no new issues arise from downgrading the "azure-ai-ml" package.
4. Confirm that the functionality of the AI Hub scripts works as expected after the package change.
> build: Downgrade azure-ai-ml package to compatible version

- ResearchAssistant/Deployment/scripts/aihub_scripts/requirements.txt
* This PR upgrade the "azure-ai-ml" package to version 1.23.1 to resolve version conflicts that were causing deployment failures related to AI Hub scripts.
- Verify that the package version upgrade to 1.23.1 is applied successfully.
- Test the deployment process to ensure the issue with AI Hub scripts failing due to package conflicts is resolved.
- Ensure that no new issues arise from upgrading the "azure-ai-ml" package.
- Confirm that the functionality of the AI Hub scripts works as expected after the package change.
> build: Upgrade azure-ai-ml package to compatible version

- .github/workflows/build-docker.yml
Implement Consistent Versioning and Tagging for Accelerator Images
[User Story 12923](https://dev.azure.com/CSACTOSOL/CSA%20Solutioning/_workitems/edit/12923): [POC]Ensure Consistent Image Versioning Client Advisor Accelerator
Verify that image version getting updated
> feat: Implement Consistent Versioning and Tagging for Accelerator Images

- ClientAdvisor/App/frontend/src/components/ChatHistory/ChatHistoryPanel.module.css
> fix: fixed the UI issue in Chat history list section

- ClientAdvisor/App/frontend/package-lock.json
- ClientAdvisor/App/frontend/package.json
Reverts microsoft/Build-your-own-copilot-Solution-Accelerator#248
> fix: Revert "build: bump @typescript-eslint/eslint-plugin from 6.21.0 to 8.19.0 in /ClientAdvisor/App/frontend"

- .github/workflows/CAdeploy.yml
- .github/workflows/RAdeploy.yml
- .github/workflows/build-clientadvisor.yml
- .github/workflows/build-researchassistant.yml
- .github/workflows/pr-title-checker.yml
- .github/workflows/pylint.yml
- .github/workflows/stale-bot.yml
- .github/workflows/test_client_advisor.yml
This pull request includes multiple changes to the GitHub workflows to improve naming consistency and add new triggers. The most important changes include renaming workflows for clarity, adjusting cron schedules, and adding the `workflow_dispatch` trigger to specific workflows.
* [`.github/workflows/CAdeploy.yml`](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468L1-R1): Renamed workflow to "Validate Deployment - Client Advisor" for better clarity.
* [`.github/workflows/RAdeploy.yml`](diffhunk://#diff-752e6c51411766596494ef842fac2f6094759426c2db70f0d665943a9438cb2eL1-R1): Renamed workflow to "Validate Deployment - Researcher" for consistency.
* [`.github/workflows/build-clientadvisor.yml`](diffhunk://#diff-1f4a4ae6e28cf60a0f62c913d89ecb51555ff0098f9ca305cccd7 …
> chore: Updated workflow names and trigger schedule

- .github/workflows/test_research_assistant.yml
This pull request includes a small change to the `.github/workflows/test_research_assistant.yml` file. The change updates the workflow name for clarity and consistency.
* ...
> chore: updated researcher unit test workflow name

- ResearchAssistant/App/frontend/package-lock.json
- ResearchAssistant/App/frontend/package.json
The purpose of this user story is to ensure that dependency updates made by in the dependabotchanges branch are correctly validated and integrated into the main branch of the BYOC-ResearchAssistant Accelerator.
* ...
> build: validated and updated dependency for BYOC-ResearchAssistant Accelerator.

- .github/workflows/CAdeploy.yml
- ClientAdvisor/Deployment/scripts/checkquota.sh
* ...
This pull request introduces several significant changes to the deployment workflow, focusing on quota checks and dynamic region selection for Azure deployments. The most important changes include adding a new quota check script, modifying the deployment workflow to handle quota failures, and updating the resource group and deployment location parameters.
* Added a new step to run a quota check script in the deployment workflow (`.github/workflows/CAdeploy.yml`). This step ensures that the necessary Azure resources have sufficient quota before proceeding with the deployment.
* Introduced a notification step that sends an email if the quota check fails, informing the team about the issue and providing a link to the build URL.
* Added a step to fail the pipeline if the quota check …
> ci: implement quota check in CI Pipeline to ensure resource availability in supported region

- README.md
> fix: Typo in README File.

- .github/workflows/RAdeploy.yml
**Unique Resource Group Generation:**
The workflow now creates a unique resource group name by combining a predefined account name with a short UUID. This ensures that each deployment uses a distinct resource group, reducing conflicts and aiding in resource tracking.
**Conditional Cleanup:**
After deletion, the workflow verifies whether the resource group still exists before attempting any resource listing. If the group exists, it performs resource checks (including for KeyVaults, OpenAI, and MultiService resources) with a retry mechanism. If the resource group is already deleted, it logs a message and skips the resource listing step, preventing errors from querying a non-existent group.
* ...
> ci: Unique Resource Group Generation and Conditional Cleanup in GitHub Actions

- README.md
* This pull request includes changes to the `README.md` file to update image and file paths, ensuring consistency and correctness throughout the document. The updates primarily involve changing paths from `Deployment` to `docs`.
Updates to image and file paths:
* Updated the image path for the "User story" section.
* Updated the image paths for the "Key features" and "Landing Page" sections.
* Updated the image path for the "Solution accelerator architecture" section.
* Updated the deployment button link and image paths for the "Quick deploy" section.
* Updated the image path for the "Customer truth" section.
* ...
> fix: Fixing link for ca

- README.md
- infra/bicep/deploy_aihub_scripts.bicep
- infra/bicep/deploy_fabric_scripts.bicep
- infra/bicep/deploy_index_scripts.bicep
- infra/bicep/deploy_post_deployment_scripts.bicep
- infra/bicep/deploy_upload_files_script.bicep
- infra/bicep/main.json
- infra/scripts/copy_kb_files.sh
- infra/scripts/run_create_index_scripts.sh
- infra/scripts/run_fabric_items_scripts.sh
- src/AzureFunction/function_app.py
* This pull request includes several changes to update file paths and script locations across multiple files. The most important changes involve updating image paths in the `README.md` file, modifying script paths in Bicep deployment files, and adjusting URLs in various shell scripts.
Updates to image paths in `README.md`:
* Changed the image paths from `Deployment/images/readMe/` to `docs/images/readMe/` for various images such as `userStory.png`, `keyfeatures.png`, `landing_page.png`, `quickDeploy.png`, `architecture.png`, `armDeployment.png`, `supportingDocuments.png`, and `customerTruth.png`. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L7-R7) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L31-R40) …
> fix: link updated for post deployment scripts

- infra/bicep/deploy_ai_foundry.bicep
- infra/bicep/deploy_app_service.bicep
- infra/bicep/deploy_azure_function.bicep
- infra/bicep/deploy_cosmos_db.bicep
- infra/bicep/deploy_keyvault.bicep
- infra/bicep/deploy_post_deployment_scripts.bicep
- infra/bicep/deploy_sql_db.bicep
- infra/bicep/main.bicep
- infra/bicep/main.json
This pull request includes several changes to the Bicep files for deploying various Azure resources. The primary changes adding aifoundry Bicep changes including updating parameter values, commenting out unused parameters and resources, and adding new parameters and outputs. The most important changes include updates to the `deploy_app_service.bicep`, `deploy_azure_function.bicep`, `deploy_keyvault.bicep`, and `deploy_sql_db.bicep` files.
* Updated `HostingPlanSku` parameter from 'P0v3' to 'B2'.
* Commented out `ApplicationInsightsName` parameter and related resource definition. [[1]](diffhunk://#diff-a4ed21db444da5f3c124375523b1bf3b4d64fb2bc8575463f897b554e6812554L18-R24) [[2]](diffhunk://#diff-a4ed21db444da5f3c124375523b1bf3b4d64fb2bc8575463f897b554e6812554L401-R413)
* Added `@secure()` …
> feat: AI Foundry related bicep changes

- docs/FabricDeployment.md
- infra/scripts/fabric_scripts/requirements.txt
- infra/scripts/fabric_scripts/run_fabric_items_scripts.sh
* 
This pull request includes updates to the `infra/scripts/fabric_scripts` directory, specifically modifying the `requirements.txt` file and the `run_fabric_items_scripts.sh` script. The most important changes are as follows:
* Added the `packaging` library to the `requirements.txt` file.
* Changed the `pip install` command in `run_fabric_items_scripts.sh` to use the `--user` flag for installation.
* ...
> fix: Fixing pip package issue

- docs/AIFoundryDeployment.md
- docs/FabricDeployment.md
- docs/PromptFlowEvaluation.md
- docs/PromptFlowSafetyEvaluation.md
- infra/bicep/deploy_aihub_scripts.bicep
- infra/bicep/deploy_fabric_scripts.bicep
- infra/bicep/deploy_index_scripts.bicep
- infra/bicep/deploy_upload_files_script.bicep
- infra/bicep/main.json
- infra/scripts/copy_kb_files.sh
- infra/scripts/run_create_aihub_scripts.sh
- infra/scripts/run_create_index_scripts.sh
- infra/scripts/run_fabric_items_scripts.sh
- src/WebApp.Dockerfile
* ...
This pull request includes updates to various documentation and script files, primarily to update file paths and URLs for images and scripts. The most important changes include updating image paths in documentation files and script URLs in deployment scripts.
Documentation updates:
* [`docs/AIFoundryDeployment.md`](diffhunk://#diff-63c9e4ba81bb5f7eefc488d6e868b0baacd544a8636cd8ffdc54e34b33585321L7-R68): Updated image paths from `/ResearchAssistant/Deployment/images/aiStudio/` to `/docs/images/aiStudio/`. [[1]](diffhunk://#diff-63c9e4ba81bb5f7eefc488d6e868b0baacd544a8636cd8ffdc54e34b33585321L7-R68) [[2]](diffhunk://#diff-63c9e4ba81bb5f7eefc488d6e868b0baacd544a8636cd8ffdc54e34b33585321L77-R137)
* [`docs/FabricDeployment.md`](diffhunk://#diff-ec9f7472bd409561aeb81e8775f4899a289b0de33213 …
> feat: added new paths

- .github/workflows/Create-Release.yml
This pull request introduces a new GitHub Actions workflow to automate the creation of releases using Semantic Release. The workflow is designed to run on pushes to the `main` branch and leverages the `semantic-release` tool to generate version tags, release notes, and GitHub releases based on conventional commit messages.
* **File: `.github/workflows/Create-Release.yml`**
- Added a new workflow named `Create-Release` that triggers on pushes to the `main` branch.
- Configured permissions for `contents` and `pull-requests` to `write`.
- Added a job (`create-release`) to:
- Check out the repository using `actions/checkout@v4`.
- Use the `codfish/semantic-release-action@v3` to automate versioning and changelog generation based on conventional commits. This includes custom configurations for …
> ci: Create Create-Release.yml

- infra/scripts/add_cosmosdb_access.sh
- infra/scripts/add_user_scripts/create_sql_user_and_role.sh
- infra/scripts/checkquota.sh
- infra/scripts/copy_kb_files.sh
- infra/scripts/process_sample_data.sh
- infra/scripts/quota_check_params.sh
- infra/scripts/run_create_index_scripts.sh
- infra/scripts/run_fabric_items_scripts.sh
adds back post deployment scripts with Unix Style End of Line Sequence (LF)
* ...
> fix: added back post deployment scripts with Unix Style line endings (LF)

- ResearchAssistant/Deployment/scripts/aihub_scripts/requirements.txt
This pull request updates the version of a dependency in the `requirements.txt` file to ensure compatibility with the latest features and bug fixes.
Dependency update:
* [`ResearchAssistant/Deployment/scripts/aihub_scripts/requirements.txt`](diffhunk://#diff-1e7bc97a57939ba3368c837d3b4787f87b8079ffa142ff56ed5a91bb933478c0L4-R4): Updated the version of the `azure-ai-ml` library from `1.26.1` to `1.26.3`.
* ...
> fix: azure-ai-ml SDK and CLI installation broken

- README.md
> docs: readme documentation changes

- .devcontainer/devcontainer.json
…sh files
Update postCreateCommand to replace line feed chars to support linux env.
* ...
Rebuild DevContainer
> fix: update devcontinaer postCreateCommand to update line feed chars in sh files

- TRANSPARENCY_FAQ.md
- docs/FabricDeployment.md
- docs/SampleQuestions.md
- src/App/frontend/src/components/Answer/Answer.test.tsx
- src/App/frontend/src/pages/layout/Layout.test.tsx
Identified the typo error in the README.md file and corrected it.
> fix:  Identify the typo error and corrected

- infra/deploy_ai_foundry.bicep
[Bicep deployment fails with ApiPropertiesInvalid error related to statisticsEnabled · Issue #17032 · Azure/bicep](https://github.com/Azure/bicep/issues/17032)
To avoding the error, should comment apiProperties in the aiServices 'Microsoft.CognitiveServices/accounts@2021-10-01'
* ...
* ...
> fix: comment 'apiProperties' to avoiding error in deployment

- src/.dockerignore
- This PR introduces a .dockerignore file within the src directory, which serves as the Docker build context. It ensures that unnecessary files and directories—such as virtual environments, build artifacts, logs, node_modules, and IDE configurations—are excluded from being sent to the Docker daemon during the image build process.
- Optimizing the build context improves performance and reduces image size and build time.
Verify that the following are valid:
- Confirm .dockerignore is present inside src/ directory.
- Ensure expected files (e.g. .git, node_modules, .env, .vscode, etc.) are excluded from build context.
- Run a Docker build and verify only necessary files are included.
- Confirm no unintended exclusions (like source code or Dockerfile used for build)
> build: Add .dockerignore to optimize Docker build context

- .github/workflows/CAdeploy.yml
This pull request updates the `.github/workflows/CAdeploy.yml` file to enhance environment variable management, improve deployment parameter handling, and ensure better workflow resilience by adjusting conditional checks. Below are the key changes grouped by theme:
* Added `GPT_MIN_CAPACITY` and `TEXT_EMBEDDING_MIN_CAPACITY` as environment variables at the workflow level, replacing hardcoded values with dynamic references in deployment scripts. [[1]](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468R10-R13) [[2]](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468L25-R30)
* Updated the deployment script to include `gptDeploymentCapacity` and `embeddingDeploymentCapacity` parameters, leveraging the newly defined environment …
> fix: fix deployment pipeline

- src/App/backend/chat_logic_handler.py
* Not getting date and time of the next scheduled meeting in response issue fixed. Kernel function ChatWithSQLDatabase now returns the next meeting date and time in the response.
* ...
> fix: meeting scheduled date time response issue

- .github/workflows/build-docker.yml
* ...
This pull request includes a minor change to the `.github/workflows/build-docker.yml` file. The change updates the `DOCKER_PASSWORD` secret to no longer be required for the workflow.
* ...
> ci: fix workflow to skip Docker login when password is not provided

- .github/dependabot.yml
- infra/deploy_app_service.bicep
- infra/main.bicep
- infra/main.json
- src/App/.env.sample
- src/App/app.py
- src/App/backend/chat_logic_handler.py
- src/App/tests/backend/test_utils.py
- src/App/tests/test_app.py
This pull request includes significant updates to the infrastructure configuration files, focusing on simplifying the deployment parameters and removing unused or redundant settings. These changes aim to streamline the deployment process and reduce complexity.
* Removed the `AzureSearchIndexIsPrechunked` parameter and its associated references across multiple files, as it is no longer required. (`infra/deploy_app_service.bicep` [[1]](diffhunk://#diff-37c8b5694d17291d641a19fb8a562e30642066b4bf8b8657f2636f50567cf4ebL35-L37) `infra/main.bicep` [[2]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L203-L213) `infra/main.json` [[3]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L2142-L2144) …
> refactor: Cleanup the unused variables in all the files

- tests/e2e-test/README.md
- tests/e2e-test/requirements.txt
- tests/e2e-test/tests/conftest.py
- tests/e2e-test/tests/test_poc_byoc_client_advisor.py
Implemented Log execution time per prompt in Report
> test: Implemented Log execution time per prompt in Report

- tests/e2e-test/pages/homePage.py
- tests/e2e-test/tests/test_poc_byoc_client_advisor.py
Implemented Log execution time per prompt in Report
> test: Implemented Log execution time per prompt in Report 

- src/App/backend/agents/agent_factory.py
- src/App/backend/plugins/chat_with_data_plugin.py
- src/App/tests/backend/agents/test_agent_factory.py
- src/App/tests/backend/plugins/test_chat_with_data_plugin.py
This pull request refines the behavior of the Wealth Advisor agent by updating its instructions and removing a redundant plugin method for handling greetings. These changes streamline the agent's functionality and improve its conversational capabilities.
* [`src/App/backend/agents/agent_factory.py`](diffhunk://#diff-ceceeaf6b7bac47e276ae594ac9d58cb0c2de4198350caa13ca04f2dfabe67c0L44-R45): Enhanced the `agent_instructions` for the Wealth Advisor agent to include handling conversational, non-data-related queries (e.g., greetings or follow-ups) in an appropriate context.
* [`src/App/backend/plugins/chat_with_data_plugin.py`](diffhunk://#diff-001f08f4587512646a0f76e81b34d4f41b480331d9adb85894d4ef30036a0605L25-L60): Removed the `greeting` method, which handled greeting responses, as this …
> refactor: Remove greeting kernel function and Update orchestrator agent to handle greetings

- src/App/backend/agents/agent_factory.py
- src/App/backend/plugins/chat_with_data_plugin.py
- src/App/tests/backend/plugins/test_chat_with_data_plugin.py
* ...
This pull request introduces a new SQL agent for generating T-SQL queries and refactors the logic for handling SQL query generation and execution. The changes improve modularity, reusability, and error handling in the codebase.
* Added a `get_sql_agent` class method in `AgentFactory` to create or retrieve a singleton SQLQueryGenerator AzureAIAgent instance. This agent uses a predefined schema and rules to generate T-SQL queries from natural language input. (`src/App/backend/agents/agent_factory.py`, [src/App/backend/agents/agent_factory.pyR109-R151](diffhunk://#diff-ceceeaf6b7bac47e276ae594ac9d58cb0c2de4198350caa13ca04f2dfabe67c0R109-R151))
* Replaced the inline SQL prompt generation logic in `get_SQL_Response` with the new `get_sql_agent` method. This centralizes the agent creation …
> feat: integrate agent sdk into the kernel function

- infra/deploy_ai_foundry.bicep
- infra/main.bicep
- infra/main.json
- infra/scripts/checkquota.sh
- infra/scripts/quota_check_params.sh
* ...
This pull request updates the AI model deployment configurations and associated scripts to use the `GlobalStandard` SKU instead of the `Standard` SKU for better alignment with the latest Azure offerings. The changes span multiple files, including deployment templates and quota-checking scripts.
* Updated the `sku.name` for embedding models from `Standard` to `GlobalStandard` in `infra/deploy_ai_foundry.bicep` and `infra/main.json`. [[1]](diffhunk://#diff-801321770c4260aea129a24ab905704034ec515f2811ee5d93a6fc7c2d29c626L40-R40) [[2]](diffhunk://#diff-0504f5a35afecd5c8c2a1dc8cac5bb558cc1456c557d8edcb7f9bac1c0dc36e4L1041-R1041)
* Changed the `usageName` for the `text-embedding-ada-002` model to reflect the `GlobalStandard` SKU in `infra/main.bicep` and `infra/main.json`. …
> feat: migrate model types to GlobalStandard

- .github/dependabot.yml
- docs/DeploymentGuide.md
- infra/main.bicep
> chore: Down merge from main to dev

- .github/workflows/CAdeploy.yml
- infra/scripts/process_sample_data.sh
- infra/scripts/run_create_index_scripts.sh
This pull request makes minor adjustments to deployment and infrastructure scripts, primarily focusing on environment variable handling and script cleanup. The changes help ensure consistency in variable names and remove unused code.
Environment variable handling:
* [`.github/workflows/CAdeploy.yml`](diffhunk://#diff-67593888fa4a3b8c26f65fe9387615f60cda88c80b3eb1407e6330d5e8bb1468L156-R156): Fixed a typo in the JSON key used to extract `AI_FOUNDRY_RESOURCE_ID` from deployment output, ensuring the correct variable is set in the environment.
Script cleanup:
* [`infra/scripts/process_sample_data.sh`](diffhunk://#diff-5f42277e379c1334fbdc9a52828c031d1620d82b99cded3dc825000a68e0ae0cL54-L57): Removed unused code that set the `aiFoundryName` variable, as it is no longer needed in the script.
* …
> ci: Fixed the Deployment Pipeline

- docs/DeploymentGuide.md
The change made in the deploymentMd file is an update to the description for the **AZURE\_LOCATION** variable. The new description clarifies that the Azure region is selected by the user during deployment:
* ...
> docs: Azure Region Selection Updated in Deployment.Md Docs

- infra/main.bicep
- infra/main.json
This pull request updates the infrastructure deployment configuration to improve region selection, parameter consistency, and maintainability. The main changes include restricting and renaming the Azure region parameter, updating variable and parameter usage to match, and making minor prompt formatting and dependency adjustments.
**Region and Parameter Configuration:**
* Restricted the allowed Azure regions for deployment by replacing the `AZURE_LOCATION` parameter with a new required `location` parameter, which only accepts a specific list of compatible regions. Updated descriptions and added metadata for better clarity and tooling support. (`infra/main.bicep`, `infra/main.json`) [[1]](diffhunk://#diff-7ef659fc9cf6968e718894d300490b14ea7a52091e7d4bcffae3a5029ac721d4L85-R98) …
> chore: update location parameter to enforce allowed Azure regions

- infra/scripts/index_scripts/create_grants_index.py
* This pull request makes a minor change to the secret retrieval logic in `infra/scripts/index_scripts/create_grants_index.py`. The unnecessary retrieval of the `AZURE-CLIENT-ID` secret has been removed, streamlining the script.
* ...
> fix: Remove redundant retrieval of Azure client ID from Key Vault in create_grants_index.py
